# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_auto_20180923_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpass',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 16, 1, 29, 375632), verbose_name='用户提交时间'),
        ),
    ]
